[project]
name = 'loandao'
description = ''
authors = [NoCodeClarity]
telemetry = true
cache_dir = './.cache'
requirements = [Change the World]
[contracts.loandao]
path = 'contracts/loandao.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
